routes:
  - name: "Test"
    prefix: "test"
    path: "./test"

  - name: "Assignment"
    prefix: "assignment"
    path: "./assignment"

  - name: "Books"
    prefix: "books"
    path: "./books"

  - name: "BidPro"
    prefix: "bidpro"
    path: "./bidpro"
